Controllers/ApplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using GetJobsv3.Models;

namespace GetJobsv3.Controllers
{
    public class ApplyController : Controller
    {
        GetJobsModel db = new GetJobsModel();

        #region display job posts
        // GET: Apply
        public ActionResult DisplayJobPosts()
        {
            var posts = GetAllActivePost();
            if(posts != null)
            {
                return View(posts);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        IEnumerable<Job> GetJobList()
        {
            return db.Jobs.ToList<Job>();
        }
        public List<Job> GetAllActivePost()
        {
            //get db info from GetJobModel for job posting
            List<JobPosting> jpList = db.JobPostings.ToList();
            //get db info from GetJobModel for job via the IEnumerable method
            IEnumerable<Job> jList = GetJobList();
            //create a list to store only the active job posts
            List<Job> activeJobList = new List<Job>();
            foreach(var jp in jpList)
            {
                //if job posting is active 
                if(jp.IsActive)
                {
                    foreach(var j in jList)
                    {
                        //job posting's job id matches job's job id
                        if(jp.JobID == j.jobID)
                        {
                            //add it to the active list
                            activeJobList.Add(j);
                        }
                    }
                }
            }
            return activeJobList;

        }
        #endregion



    }
}

Controllers/JobAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GetJobsv3.Models;
using System.Net;

namespace GetJobsv3.Controllers
{
    public class JobAppController : Controller
    {
        Applicant a = new Applicant();
        List<Employer> empList = new List<Employer>();
        //create list to hold all the active postings
        List<JobPosting> jpList = new List<JobPosting>();
        //instantiate MidTier to access its methods 
        MidTier mt = new MidTier();

        //dbContext created by Entity Framework
        private GetJobsModel db = new GetJobsModel();
      
        // GET: JobApp
        public ActionResult ViewAllJobPostings()
        {
            var posts = GetAllPosts();
            if(posts != null)
            {
                return View(posts);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

        }
        public List<Job> GetAllPosts()
        {
            List<JobPosting> jpList = db.JobPostings.ToList();
            IEnumerable<Job> jList = GetJobs();
            List<Job> activePosts = new List<Job>();
            foreach(var jp in jpList)
            {
                foreach(var j in jList)
                {
                    if(jp.IsActive)
                    {
                        activePosts.Add(j);
                    }

                }
            }
            return activePosts;
        }
        IEnumerable<Job> GetJobs()
        {
          return db.Jobs.ToList<Job>();  
        }


        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job =  db.Jobs.Find(id);
            if(job == null)
            {
                return HttpNotFound();
            }         
            return View(job);
        }

        public ActionResult Apply()
        {          
            Applicant a = new Applicant();                    
            return View(a);
        }
       

        public void insertApp()
        {


            int archive = 0;
            int emailed = 0;
            //call db to insert applicant
            int insertEmp = 0, insertEdu = 0;
            int insertApp = mt.insertApplicant(a.JobPostingID , a.FirstName , a.MiddleName , a.LastName , a.Street , a.City , a.StateName , a.Zip , a.Phone1 , a.Phone2 , a.Email , a.BestWay2contact , a.LinkedIn , a.ResumeName , a.ResumePath , a.ASign , a.SubmittedDate , archive , emailed);
            if(insertApp < 0)
            {
                return;

            }
            #region work history pages
            int emnohis = 0; int emcur = 0; int emcont = 0;
            string emcom = ""; string emjti = ""; string emcit = ""; string emsta = ""; string emph = ""; string emfn = ""; string emln = ""; string emdut = ""; string emleav = ""; string startS = ""; string endS = "";
            DateTime? emstar; DateTime? emend;
            if(a.EmpList != null && a.EmpList.Count() > 0)
            {
                foreach(Employer em in a.EmpList)
                {
                    if(em.NoWorkHis == true)
                    {
                        break;
                    }
                    if(em.NoWorkHis == false)
                    {
                        if(String.IsNullOrEmpty(em.Company))
                        {
                            emcom = DBNull.Value.ToString();
                        }
                        else { emcom = em.Company; }
                        if(String.IsNullOrEmpty(em.JobTitle))
                        {
                            emjti = DBNull.Value.ToString();
                        }
                        else { emjti = em.JobTitle; }

                        emstar = em.StartDate;
                        emend = em.EndDate;
                        if(String.IsNullOrEmpty(em.City))
                        {
                            emcit = DBNull.Value.ToString();
                        }
                        else { emcit = em.City; }

                        if(String.IsNullOrEmpty(em.StateName))
                        {
                            emsta = DBNull.Value.ToString();
                        }
                        else { emsta = em.StateName; }

                        if(String.IsNullOrEmpty(em.Phone))
                        {
                            emph = DBNull.Value.ToString();
                        }
                        else { emph = em.Phone; }

                        if(String.IsNullOrEmpty(em.SuperFName))
                        {
                            emfn = DBNull.Value.ToString();
                        }
                        else { emfn = em.SuperFName; }

                        if(String.IsNullOrEmpty(em.SuperLName))
                        {
                            emln = DBNull.Value.ToString();
                        }
                        else { emln = em.SuperLName; }

                        if(String.IsNullOrEmpty(em.JobDuties))
                        {
                            emdut = DBNull.Value.ToString();
                        }
                        else
                        {
                            emdut = em.JobDuties;
                        }
                        if(String.IsNullOrEmpty(em.ReasonLeave))
                        {
                            emleav = DBNull.Value.ToString();
                        }
                        else
                        {
                            emleav = em.ReasonLeave;
                        }
                        if(em.CurrentJob == true)
                        {
                            emcur = 1;
                        }
                        if(em.ContactEmp == true)
                        {
                            emcont = 1;
                        }
                        if(String.IsNullOrEmpty(em.StartSal))
                        {
                            startS = DBNull.Value.ToString();
                        }
                        else { startS = em.StartSal; }
                        if(String.IsNullOrEmpty(em.EndSal))
                        {
                            endS = DBNull.Value.ToString();
                        }
                        else { endS = em.EndSal; }
                        //End work history
                        //call db to insert each employer
                        insertEmp = mt.insertEmployer(insertApp , emnohis , emcom , emjti , emstar , emend , emcur , emcit , emsta , emph , emfn , emln , emdut , emcont , emleav , startS , endS);
                        if(insertEmp < 0)
                        {
                            return;
                        }

                    }
                    #region education
                    //education page
                    string edname = "", edcity = "", edsta = "", edzip = "", eddeg = "";
                    DateTime? edstar, edend;
                    int edgrad = 0;
                    foreach(Education ed in a.EduList)
                    {
                        if(!String.IsNullOrEmpty(ed.SchoolName))
                        {
                            edname = ed.SchoolName;
                            edcity = ed.City;
                            edsta = ed.StateName;
                            edzip = ed.Zip;
                            edstar = ed.StartDate;
                            edend = ed.EndDate;
                            if(ed.Graduate == true)
                            {
                                edgrad = 1;
                            }
                            eddeg = ed.Degree;
                            //call db insert each education
                            insertEdu = mt.insertEducation(insertApp , edname , edcity , edsta , edzip , edstar , edend , edgrad , eddeg);
                            if(insertEdu < 0)
                            {
                                return;
                            }
                        }

                    }
                    #endregion
                    if(insertApp > 0)
                    {

                    }
                    else
                    {

                    }


                }

            }
            #endregion

        }
    }
}

Views/JobApp/Apply.cshtml
@model GetJobsv3.Models.Applicant
@{
    ViewBag.Title = "Powers Painting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using(Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Applicant</h4>
        <hr />
        @Html.ValidationSummary(true , "" , new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.FirstName , "First Name: " , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName , "Middle Name: " , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName , "Last Name: " , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street , "Street: " , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateName , "State:" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateName , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateName , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone1 , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone1 , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone1 , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone2 , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone2 , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone2 , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BestWay2contact , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BestWay2contact , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BestWay2contact , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LinkedIn , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LinkedIn , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LinkedIn , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ASign , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ASign , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ASign , "" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List" , "ViewAllJobPostings")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/JobApp/Details.cshtml
@model GetJobsv3.Models.Job
@{
    ViewBag.Title = "Powers Painting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h4> @Html.DisplayFor(model => model.JobTitle)</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreferredSkills)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreferredSkills)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EoeMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EoeMessage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List" , "ViewAllJobPostings")

    @Html.ActionLink("Apply for Job" , "Apply")
</p>

Views/JobApp/ViewAllJobPostings.cshtml
@model IEnumerable<GetJobsv3.Models.Job>
@{
    ViewBag.Title = "Powers Painting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
        <div id="careers" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="marg25 service-name">
                        <p>Job Openings</p>
                        <table class="table table-responsive table-bordered">

                            @foreach(var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.JobTitle)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Details" , "Details" , new { id = item.jobID })
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
>
